import Head from 'next/head'
import React from 'react'
import Home from './main/home'

function index() {
  return (
    <div>  
        <Head>
          <title>Dompetku Next JS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="../public/dompetku.png" />
        </Head>

       <Home />
  </div>
  )
}

export default index